### PR TITLE
Gradio & Studio update

### PR DESCRIPTION
**Pull request by ollmer**
- update gradio, bump to the fresh version without vulnerabilities
- fix agent update from config, instantiate correct nodes, just like subagents
- make studio work with state containing dicts instead of agent and tape objects

### CODE REVIEW

**Review by rizar — APPROVED** [review]
I only have naming suggestions, LGTM otherwise

**Comment by ollmer** [comment]
This also closes #81

**Comment by jpt-sn** [comment]
Do we really need to model_dumps and model_validate every time? 

From the Gradio [documentation](https://www.gradio.app/guides/state-in-blocks#:~:text=So%20if%20you%20define%20a%20custom%20class%20and%20create%20a%20gr.State%20variable%20that%20is%20an%20instance%20of%20that%20class%2C%20make%20sure%20that%20the%20the%20class%20includes%20a%20sensible%20__hash__%20implementation.) it says:
> If it holds an object or primitive, a change is triggered if the hash of the value changes. So if you define a custom class and create a gr.State variable that is an instance of that class, make sure that the the class includes a sensible `__hash__` implementation.

Have we tried implementing the `__hash__` for tape and agent object?

**Comment by ollmer** [comment]
Yes, I've tried to implement `__hash__()` for the agent class, which returned agent.model_dump_json(). It didn't help.
Also in case of the absence of a hash method the state raises error when created, and we haven't observe such issute.

**Pull request merged**
